# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1337fcea5742b951e821d93c79ae160d43cf69c82b8d7062de7bacbc765f6d9bdd708dbcc4aea1bf512f4a564e5e962e1614f0603cd39ab7918924abffdceff

test:
  secret_key_base: 890ca6804e2d60dfad332c4515a865e743cf6f357fb19e98aa80da81bc890955810d055c0c13b975c1af889fcb03a9ac9be39f23b666aa48b0b97dc2cb12fbc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
